### PR TITLE
mge standard nocontam

### PR DESCRIPTION
**Pull request by SchistoDan**

### CODE REVIEW

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Error processing PR 40: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/naturalis/barcode_validator/issues/40/comments
Stack trace:
Traceback (most recent call last):
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 76, in process_pr
    self.post_pr_results(config, pr_number, results)
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 223, in post_pr_results
    self.gc.post_comment(pr_number, comment)
  File "/data/rutger.vos/barcode_validator/barcode_validator/github.py", line 52, in post_comment
    response.raise_for_status()
  File "/data/rutger.vos/conda/miniconda3/envs/barcode_validator/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/naturalis/barcode_validator/issues/40/comments

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Error processing PR 40: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/naturalis/barcode_validator/issues/40/comments
Stack trace:
Traceback (most recent call last):
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 76, in process_pr
    self.post_pr_results(config, pr_number, results)
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 223, in post_pr_results
    self.gc.post_comment(pr_number, comment)
  File "/data/rutger.vos/barcode_validator/barcode_validator/github.py", line 52, in post_comment
    response.raise_for_status()
  File "/data/rutger.vos/conda/miniconda3/envs/barcode_validator/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/naturalis/barcode_validator/issues/40/comments

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Error processing PR 40: endswith first arg must be str or a tuple of str, not list
Stack trace:
Traceback (most recent call last):
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 78, in process_pr
    results = self.validate_pr(config, pr_number, branch)
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 132, in validate_pr
    fasta_files = self.gc.fetch_pr_files(branch, pr_number, ['.fasta', '.fa', '.fas'])
  File "/data/rutger.vos/barcode_validator/barcode_validator/github.py", line 65, in fetch_pr_files
    matching_files = [f for f in files if f['filename'].endswith(extensions)]
  File "/data/rutger.vos/barcode_validator/barcode_validator/github.py", line 65, in <listcomp>
    matching_files = [f for f in files if f['filename'].endswith(extensions)]
TypeError: endswith first arg must be str or a tuple of str, not list

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Error processing PR 40: string indices must be integers
Stack trace:
Traceback (most recent call last):
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 79, in process_pr
    results = self.validate_pr(config, pr_number, branch)
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 143, in validate_pr
    results = self.bv.validate_fasta(file['filename'], config)
TypeError: string indices must be integers

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Error processing PR 40: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/naturalis/barcode_validator/issues/40/comments
Stack trace:
Traceback (most recent call last):
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 80, in process_pr
    self.post_pr_results(config, pr_number, results)
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 247, in post_pr_results
    self.gc.post_comment(pr_number, comment)
  File "/data/rutger.vos/barcode_validator/barcode_validator/github.py", line 105, in post_comment
    response.raise_for_status()
  File "/data/rutger.vos/conda/miniconda3/envs/barcode_validator/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/naturalis/barcode_validator/issues/40/comments

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Error processing PR 40: Git command failed: git commit -m Validated FASTA file data/mge_fastp_r13s100_nocontam.fasta for #PR40
Stack trace:
Traceback (most recent call last):
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 80, in process_pr
    self.post_pr_results(config, pr_number, results)
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 239, in post_pr_results
    self.gc.commit_file(file, f"Validated FASTA file {file} for #PR{pr_number}")
  File "/data/rutger.vos/barcode_validator/barcode_validator/github.py", line 130, in commit_file
    self.run_git_command(['git', 'commit', '-m', message], f"Failed to commit {filename}")
  File "/data/rutger.vos/barcode_validator/barcode_validator/github.py", line 119, in run_git_command
    raise RuntimeError(f"Git command failed: {' '.join(command)}")
RuntimeError: Git command failed: git commit -m Validated FASTA file data/mge_fastp_r13s100_nocontam.fasta for #PR40

**Comment by rvosa** [comment]
@SchistoDan The first word of the definition line has to be the process ID, not the word Consensus. So: `>ProcessID_...`

**Comment by SchistoDan** [comment]
@rvosa Apologies! That's now corrected in the 12 multi-fasta files.

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
🤖 - Error processing PR 40: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/naturalis/barcode_validator/issues/40/comments
Stack trace:
Traceback (most recent call last):
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 80, in process_pr
    self.post_pr_results(config, pr_number, results)
  File "/data/rutger.vos/barcode_validator/barcode_validator/daemon.py", line 247, in post_pr_results
    self.gc.post_comment(pr_number, comment)
  File "/data/rutger.vos/barcode_validator/barcode_validator/github.py", line 105, in post_comment
    response.raise_for_status()
  File "/home/rutger.vos/.conda/envs/barcode_validator/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/naturalis/barcode_validator/issues/40/comments

**Comment by rvosa** [comment]
Hi @SchistoDan, do I understand correctly that this PR is now superseded by the approach where we simply upload directly to the NHM branch? If yes, could you close this thing? Thanks!

**Pull request closed without merging**
