### PR TITLE
Added MGE outputs for benchmarking dataset

### PR DESCRIPTION
**Pull request by SchistoDan**
MGE outputs run using the 'standard' MGE snakemake pipeline run with varying (r and s) parameter combinations. See config*.yaml for info.

### CODE REVIEW

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Comment by rvosa** [comment]
Hi @SchistoDan - ignore the stack trace for now: the functionality for folding YAML and CSV into the output isn't there yet. Just leave this PR here, the example files are useful so I'll pick this up to get it to work.

**Comment by SchistoDan** [comment]
Hi @rvosa, thanks for the heads up. Would it be useful for me to create a new PR with just the consensus sequence multi-fasta so barcode_validator can get on with validating? Similarly, I can leave the YAML and CSV files out of the remaining PRs I'm going to do (today or tomorrow) to validate the MGE pipeline variants, and seeing as you have now have examples. Happy to still include them if useful.

**Comment by rvosa** [comment]
🤖 - Hi! This is an automated message from the barcode validation robot. I'm going to validate the FASTA files in your request. This takes less than two minutes per sequence (about two hours per plate). Subscribe to this thread to get updates. You can safely close this tab.

**Pull request closed without merging**
